name: Cluster Apply

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Initialize Terraform
      run: terraform -chdir="terraform/" init 
    - name: Apply Terraform
      run: terraform -chdir="terraform/" apply -auto-approve
