name: Deploy Dev

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:     
    - name: Check out repository
      uses: actions/checkout@v3  
      
    - name: debug
      run: |
        pwd
        tree
        ls -lash

    - name: Helm Install
      uses: ryanlraines/hotwing/.github/workflows/helm_install_template.yml@main
      with:
        region: 'us-east-1'
        cluster_name: 'qa'
