name: image build

on:
  workflow_dispatch:
  push:
    paths:
      - 'ops/docker/**'
      - 'src/**'

env:
  ECR_REGISTRY: 445850313110.dkr.ecr.us-east-2.amazonaws.com
  AWS_REGION: us-east-2
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Tag Docker Image
        id: build-image
        run: |
          docker build . -f ops/docker/dockerfile -t $ECR_REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: Push Docker Image to Amazon ECR
        id: push-image
        run: |
          docker push $ECR_REGISTRY/$IMAGE_NAME:${{ github.sha }}
