name: Deploy QA

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Docker Tag
      id: docker-tag
      run: |
        docker pull $ECR_REGISTRY/$IMAGE_NAME:dev
        docker tag $ECR_REGISTRY/$IMAGE_NAME:dev $ECR_REGISTRY/$IMAGE_NAME:qa
        docker push $ECR_REGISTRY/$IMAGE_NAME:qa

    - name: Helm Install 
      uses: file://.github/workflows/helm_install_template.yml
      with:
        region: 'us-east-1'
        cluster_name: 'qa'